run:
  # timeout for analysis
  timeout: 4m
  build-tags:
    - autopilotrpc
    - chainrpc
    - invoicesrpc
    - neutrinorpc
    - peersrpc
    - signrpc
    - walletrpc
    - watchtowerrpc

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false

  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    lines: 200
    # Checks the number of statements in a function.
    statements: 80

  gosec:
    excludes:
      - G402 # Look for bad TLS connection settings.
      - G306 # Poor file permissions used when writing to a new file.

  whitespace:
    multi-func: true
    multi-if: true

linters:
  enable-all: true
  disable:
    # Allow dynamic errors.
    - err113

    # We want to allow short variable names.
    - varnamelen

    # Allow tests to be put in the same package.
    - testpackage

    # We want to allow TODOs.
    - godox

    # Init functions are used by loggers throughout the codebase.
    - gochecknoinits

    # Global variables are used by loggers.
    - gochecknoglobals

    # Some lines are over 80 characters on purpose and we don't want to make
    # them even longer by marking them as 'nolint'.
    - lll

    # We don't require that all structs have all fields initialized when new
    # instances are created.
    - exhaustruct

    # Disable gofumpt as it has weird behavior regarding formatting multiple
    # lines for a function which is in conflict with our contribution
    # guidelines. See https://github.com/mvdan/gofumpt/issues/235.
    - gofumpt

    # Disable whitespace linter as it has conflict rules against our
    # contribution guidelines. See https://github.com/bombsimon/wsl/issues/109.
    #
    # TODO: bring it back when the above issue is fixed.
    - wsl

    # Deprecated linters. See https://golangci-lint.run/usage/linters/.
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unparam
    - wastedassign

    # New linters that need a code adjustment first.
    - depguard
    - testifylint
    - intrange

    # We use a replace directive for a custom protobuf library.
    - gomoddirectives

    # The linter is too aggressive and doesn't add much value since reviewers
    # will also catch magic numbers that make sense to extract.
    - mnd

issues:
  # Only show newly introduced problems.
  new-from-rev: 4008b92d81d4d62e663025c5f79ebe44b53f283c

  exclude-rules:
    # Exclude gosec from running for tests so that tests with weak randomness
    # (math/rand) will pass the linter. We also exclude funlen from tests as
    # have test functions that are intentionally long.
    - path: _test\.go
      linters:
        - gosec
        - funlen

    - path: test*
      linters:
        - gosec
        - funlen

    - path: itest/.*
      linters:
        - paralleltest
